### ISSUE TITLE
Landing page improvement

### ISSUE THREAD

**Issue by davityavryan** [locize/locize-landing#1]
Hey guys,
Would you accept an offer to rewrite your interface?
I am offering my free time to re-implement all your pages and redefine UX. It is currently hard to impress management to switch to your interface. Suggestions is to use popular and modern tools like React with Material-UI. I have experience to create everything, it's just time to time I would need help from you in order to understand the product better.

And I will do it for **FREE**. You can just put my name somewhere hidden. :)

What you would say?

**Comment by jamuhl** [comment]
Hi Davit, are you talking about locize.com the "marketing" website or locize.app the application?!?

**Comment by davityavryan** [comment]
Het @jamuhl I am talking about locize.app.
I am pretty sure that you guys are using something dynamic for Marketing website. Will be happy to discuss marketing website too with you but my proposal is to help you with locize.app.

**Comment by jamuhl** [comment]
The locize.app already is react based (react, redux, ...). We got our custom design (flat - but not material design - no need to be material at all - it's not an android app).

Not 100% sure what do you not like about the locize.app?

**Comment by davityavryan** [comment]
I am not proposing to have android app. Material design guideline does not mean same design as it is in Android app.
I am just sayin that it is hard to sell for developers to management your interface. I am just proposing to improve UI and UX.

**Comment by adrai** [comment]
Thanks @davityavryan 
We are very happy if someone wants to support us.
We are always open to suggestions for improvement.
Towards the end of the year (after the launch of [localistars.com](https://localistars.com)) we will probably start planning a larger "redesign" for locize.
Our frontend department will be happy if you would send us your comments and suggestions.
These are then checked and planned together with many other requirements.
As you probably know, UI/UX is always a controversial and debating topic.
If you want, please send an email to support@locize.com

**Comment by davityavryan** [comment]
As you wish guys. :)
I was suggesting free re-design. to a version which would have been 10 times better IMO.
I was already preparing myself for a call with you so that you would see that I am capable to change that.

Company that I work refused to change Transifex to Locize because of your interface. They argued with me that if you have that outdated interface then you probably don't bother to have anything modern. 

I personally used your npm packages in several projects and like a lot.

But ok.

![](https://media.tenor.com/images/3f36ec5b2cf77f7e26fb9640a946ccf4/tenor.gif)

**Comment by adrai** [comment]
@davityavryan As already mentioned, our frontend team is responsible for this work, we do not want to disempower them. I hope you can understand.
Nevertheless, we are really ready and happy to receive your suggestions via email.
